### ISSUE TITLE
Sketch won't compile under Arduino Core 3.0+ (updated from 2.017)

### ISSUE THREAD

**Issue by chicodaman** [SensorsIot/ESP32-Ethernet#3]
Hello Andreas - This sketch compiles perfectly under Arduino ESP Core 2.017, but after upgrading to 3.01 (using the Boards manager) it no longer compiles (as is the case, sad to see, with a fair number of other sketches...I'm trying to understand and repair them one-by-one...sigh.)

Advice? 

btw, love your youTube videos!

Compilation errors:

```
Compiling sketch...
/Users/myUserFolder/Library/Arduino15/packages/esp32/tools/esp-x32/2302/bin/xtensa-esp32-elf-g++ -MMD -c @/Users/myUserFolder/Library/Arduino15/packages/esp32/tools/esp32-arduino-libs/idf-release_v5.1-442a798083/esp32/flags/cpp_flags -Os -DF_CPU=240000000L -DARDUINO=10607 -DARDUINO_Node32s -DARDUINO_ARCH_ESP32 "-DARDUINO_BOARD=\"Node32s\"" "-DARDUINO_VARIANT=\"node32s\"" -DARDUINO_PARTITION_default "-DARDUINO_HOST_OS=\"macosx\"" "-DARDUINO_FQBN=\"esp32:esp32:node32s:UploadSpeed=921600,FlashFreq=80,PartitionScheme=default,DebugLevel=none,EraseFlash=none\"" -DESP32 -DCORE_DEBUG_LEVEL=0 -DARDUINO_USB_CDC_ON_BOOT=0 @/Users/myUserFolder/Library/Arduino15/packages/esp32/tools/esp32-arduino-libs/idf-release_v5.1-442a798083/esp32/flags/defines -I/Users/myUserFolder/Documents/Arduino/Ethernet/Andreas_Spiess/EthernetPrototype_Spiess_ORIG -iprefix /Users/myUserFolder/Library/Arduino15/packages/esp32/tools/esp32-arduino-libs/idf-release_v5.1-442a798083/esp32/include/ @/Users/myUserFolder/Library/Arduino15/packages/esp32/tools/esp32-arduino-libs/idf-release_v5.1-442a798083/esp32/flags/includes -I/Users/myUserFolder/Library/Arduino15/packages/esp32/tools/esp32-arduino-libs/idf-release_v5.1-442a798083/esp32/dio_qspi/include -I/Users/myUserFolder/Library/Arduino15/packages/esp32/hardware/esp32/3.0.1/cores/esp32 -I/Users/myUserFolder/Library/Arduino15/packages/esp32/hardware/esp32/3.0.1/variants/node32s -I/Users/myUserFolder/Library/Arduino15/packages/esp32/hardware/esp32/3.0.1/libraries/WiFi/src -I/Users/myUserFolder/Library/Arduino15/packages/esp32/hardware/esp32/3.0.1/libraries/Network/src -I/Users/myUserFolder/Documents/Arduino/libraries/PubSubClient/src -I/Users/myUserFolder/Documents/Arduino/libraries/Adafruit_Unified_Sensor -I/Users/jdu myUserFolder myUserFolder/Documents/Arduino/libraries/Adafruit_BME280_Library -I/Users/myUserFolder/Documents/Arduino/libraries/Adafruit_BusIO -I/Users/myUserFolder/Library/Arduino15/packages/esp32/hardware/esp32/3.0.1/libraries/Wire/src -I/Users/myUserFolder/Library/Arduino15/packages/esp32/hardware/esp32/3.0.1/libraries/SPI/src -I/Users/myUserFolder/Library/Arduino15/packages/esp32/hardware/esp32/3.0.1/libraries/Ethernet/src @/private/var/folders/7f/4qj_xs8117z4jzt1k609bcc40000gp/T/arduino/sketches/F88B8946125EEE3A770167DC2CB7AD10/build_opt.h @/private/var/folders/7f/4qj_xs8117z4jzt1k609bcc40000gp/T/arduino/sketches/F88B8946125EEE3A770167DC2CB7AD10/file_opts /private/var/folders/7f/4qj_xs8117z4jzt1k609bcc40000gp/T/arduino/sketches/F88B8946125EEE3A770167DC2CB7AD10/sketch/EthernetPrototype_Spiess_ORIG.ino.cpp -o /private/var/folders/7f/4qj_xs8117z4jzt1k609bcc40000gp/T/arduino/sketches/F88B8946125EEE3A770167DC2CB7AD10/sketch/EthernetPrototype_Spiess_ORIG.ino.cpp.o
/Users/myUserFolder/Documents/Arduino/Ethernet/Andreas_Spiess/EthernetPrototype_Spiess_ORIG/EthernetPrototype_Spiess_ORIG.ino:61:6: error: variable or field 'WiFiEvent' declared void
   61 | void WiFiEvent(WiFiEvent_t event)
      |      ^~~~~~~~~
/Users/myUserFolder/Documents/Arduino/Ethernet/Andreas_Spiess/EthernetPrototype_Spiess_ORIG/EthernetPrototype_Spiess_ORIG.ino:61:16: error: 'WiFiEvent_t' was not declared in this scope; did you mean 'wifi_event_t'?
   61 | void WiFiEvent(WiFiEvent_t event)
      |                ^~~~~~~~~~~
      |                wifi_event_t
/Users/myUserFolder/Documents/Arduino/Ethernet/Andreas_Spiess/EthernetPrototype_Spiess_ORIG/EthernetPrototype_Spiess_ORIG.ino:61:6: error: variable or field 'WiFiEvent' declared void
   61 | void WiFiEvent(WiFiEvent_t event)
      |      ^~~~~~~~~
/Users/myUserFolder/Documents/Arduino/Ethernet/Andreas_Spiess/EthernetPrototype_Spiess_ORIG/EthernetPrototype_Spiess_ORIG.ino:61:16: error: 'WiFiEvent_t' was not declared in this scope; did you mean 'wifi_event_t'?
   61 | void WiFiEvent(WiFiEvent_t event)
      |                ^~~~~~~~~~~
      |                wifi_event_t
/Users/myUserFolder/Documents/Arduino/Ethernet/Andreas_Spiess/EthernetPrototype_Spiess_ORIG/EthernetPrototype_Spiess_ORIG.ino: In function 'void setup()':
/Users/myUserFolder/Documents/Arduino/Ethernet/Andreas_Spiess/EthernetPrototype_Spiess_ORIG/EthernetPrototype_Spiess_ORIG.ino:189:3: error: 'WiFi' was not declared in this scope
  189 |   WiFi.onEvent(WiFiEvent);
      |   ^~~~
/Users/myUserFolder/Documents/Arduino/Ethernet/Andreas_Spiess/EthernetPrototype_Spiess_ORIG/EthernetPrototype_Spiess_ORIG.ino:189:16: error: 'WiFiEvent' was not declared in this scope; did you mean 'WiFiClient'?
  189 |   WiFi.onEvent(WiFiEvent);
      |                ^~~~~~~~~
      |                WiFiClient
/Users/myUserFolder/Documents/Arduino/Ethernet/Andreas_Spiess/EthernetPrototype_Spiess_ORIG/EthernetPrototype_Spiess_ORIG.ino:36:25: error: invalid conversion from 'int' to 'eth_phy_type_t' [-fpermissive]
   36 | #define ETH_ADDR        0
      |                         ^
      |                         |
      |                         int
/Users/myUserFolder/Documents/Arduino/Ethernet/Andreas_Spiess/EthernetPrototype_Spiess_ORIG/EthernetPrototype_Spiess_ORIG.ino:190:13: note: in expansion of macro 'ETH_ADDR'
  190 |   ETH.begin(ETH_ADDR, ETH_POWER_PIN, ETH_MDC_PIN, ETH_MDIO_PIN, ETH_TYPE, ETH_CLK_MODE);
      |             ^~~~~~~~
In file included from /Users/myUserFolder/Documents/Arduino/Ethernet/Andreas_Spiess/EthernetPrototype_Spiess_ORIG/EthernetPrototype_Spiess_ORIG.ino:5:
/Users/myUserFolder/Library/Arduino15/packages/esp32/hardware/esp32/3.0.1/libraries/Ethernet/src/ETH.h:126:29: note:   initializing argument 1 of 'bool ETHClass::begin(eth_phy_type_t, int32_t, int, int, int, eth_clock_mode_t)'
  126 |   bool begin(eth_phy_type_t type, int32_t phy_addr, int mdc, int mdio, int power, eth_clock_mode_t clk_mode);
      |              ~~~~~~~~~~~~~~~^~~~
Multiple libraries were found for "WiFiClient.h"
  Used: /Users/myUserFolder/Library/Arduino15/packages/esp32/hardware/esp32/3.0.1/libraries/WiFi
  Not used: /Users/myUserFolder/Documents/Arduino/libraries/WiFi101
  Not used: /Users/myUserFolder/Documents/Arduino/libraries/WiFiNINA
...(etc. deleted)...
exit status 1
```
Thanks...

**Comment by SensorsIot** [comment]
I would consult the current Ethernet examples and see how it has to be done. I assume I used the old example file to create this one. For example, the ETH.begin has an additional parameter (ETH_PHY_TYPE).
